# Define the conditions that trigger the pipeline.
# This pipeline is triggered on changes to the specified branches and tags.
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#ci-triggers
trigger:
  branches:
    include:
      - master
      - develop
      - release/*
  tags:
    include:
      - version/*

# Create a repository resource to the Github repo, that is providing the centrally managed CI job
resources:
  repositories:
    - repository: pwa-partner-devops
      type: github
      endpoint: INTERSHOP_GITHUB
      name: intershop/pwa-partner-devops
      ref: refs/heads/stable/v1
      # Use the following line instead if a fixed tag is preferred:
      # ref: refs/tags/1.0.0

variables:
  # Library pwa-build-configuration is provided by Intershops DevOps Environment. It provides
  # the following variables:
  #  - BUILD_AGENT_POOL:                  name of the build agent pool
  #  - REPO_SERVICE_CONNECTION:           service connection to the customer ACR
  #  - REPO_PATH:                         host name and path of the customer ACR
  - group: pwa-build-configuration

stages:
  - stage: CI
    jobs:
      # Run the CI job using the specified template, which receives input parameters based on the pwa-build-configuration library.
      # Additional custom stages/jobs may be added.
      - template: ci-job-template.yml@pwa-partner-devops
        parameters:
          # These parameters must not be changed. They are used to pass variables to the ci-job templaten, which
          # are defined by library pwa-build-configuration.
          agentPool: $(BUILD_AGENT_POOL)
          registryServiceConnection: $(REPO_SERVICE_CONNECTION)
          registry: $(REPO_PATH)